version: "3.0"

# 创建网络
networks:
  net:
    name: demo-minio-net

services:
  minio-demo:
    container_name: minio-demo
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    command: server /data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root123456
    volumes:
      - ~/data-minio-demo/data:/data
      - ~/data-minio-demo/config:/root/.minio
    ports:
      - 9000:9000
    networks:
      - net
