spring:
  application:
    name: gateway-service-zuul
server:
  port: 8080
zuul:
  routes:
    api-a:
      path: /user/v1/**
      serviceId: SERVICE-HELLOWORLD
      stripPrefix: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.120:8080/eureka/