eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: spring-cloud-zuul
server:
  port: 8080
  tomcat:
    maxThreads: 21

zuul:
  routes:
    user-api-timeout:
      path: /api/v1/user/timeout
      serviceId: spring-cloud-user
      stripPrefix: false
    shop-api-timeout:
      path: /api/v1/shop/timeout
      serviceId: spring-cloud-shop
      stripPrefix: false

# ribbon超时
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 5000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
#spring-cloud-shop:
#  ribbon:
#    ReadTimeout: 30000
#    ConnectTimeout: 10000
#    MaxAutoRetries: 0
#    MaxAutoRetriesNextServer: 0

# feign超时
feign:
  hystrix:
    enabled: true # 开启hystrix fallback

# hystrix超时
hystrix:
  command:
    default:
      fallback:
        enabled: true
#        isolation:
#          semaphore:
#            maxConcurrentRequests: 25
      execution:
        timeout:
          enabled: true # 开启hystrix timeout机制
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 6000
      circuitBreaker:
        enabled: true
    spring-cloud-user: # 指定spring-cloud-user
      fallback:
        enabled: true
#        isolation:
#          semaphore:
#            maxConcurrentRequests: 25
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 6000
      circuitBreaker:
        enabled: true
#  threadpool:
#    default:
#      allowMaximumSizeToDivergeFromCoreSize: true
#      maximumSize: 25
#    spring-cloud-user:
#      allowMaximumSizeToDivergeFromCoreSize: true
#      maximumSize: 25

logging:
  level:
    root: info