spring:
  application:
    name: spring-cloud-zuul
server:
  port: 8081

zuul:
  routes:
    api-a:
      path: /api/v1/**
      serviceId: spring-cloud-helloworld
      stripPrefix: false
  # 配置限流
  ratelimit:
    key-prefix: prefix
    enabled: true
    # 对应存储类型(用来统计存储统计信息)
    repository: BUCKET4J_INFINISPAN
    behind-proxy: true
    add-response-headers: false
    deny-request:
      response-status-code: 404 # default value is 403 (FORBIDDEN)
    # 配置路由的策略
    policy-list:
      api-a:
        - limit: 10
          # 刷新时间(单位秒)
          refresh-interval: 15
          # 根据什么统计
          type:
            - origin
            - url
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/