spring:
  application:
    name: spring-cloud-service-b
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        serviceName: ${spring.application.name}

server:
  port: 8082