eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.120:8080/eureka/
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.122:8090/dexterleslie/sc-config.git
          searchPaths: spring-cloud/config
  application:
    name: config-server